nodeLinker: node-modules

npmScopes:
  collabsoft-net:
    npmAuthToken: "${NPM_TOKEN-}"
    npmRegistryServer: "https://npm.pkg.github.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
