version: 2.1
jobs:

  prerelease:
    executor: nodejs
    steps:
      - configure
      - prerelease

  release:
    executor: nodejs
    steps:
      - configure
      - release

executors:

  nodejs:
    docker:
      - image: cimg/node:12.22.6
    working_directory: ~/iapetus

commands:

  configure:
    steps:
      - checkout:
          path: ~/iapetus

      - run:
          name: Setup environment
          command: |
            echo -e "@collabsoft-net:registry=https://npm.pkg.github.com\n//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" > ~/.npmrc
            git config user.email "github@collabsoft.net"
            git config user.name "CollabSoft Bot"

  prerelease:
    steps:
      - run: 
          name: Install dependencies
          command: npx yarn reinstall

      - run: 
          name: Publish prerelease
          command: npx yarn prerelease

  release:
    steps:
      - run: 
          name: Install dependencies
          command: npx yarn reinstall

      - run: 
          name: Publish
          command: |
            npx lerna version --conventional-commits
            npx lerna publish --from-git

workflows:
  version: 2
  deploy:
    jobs:
      - prerelease:
          filters:
            branches:
              only: develop
      - release:
          filters:
            branches:
              only: main
