version: 2.1
jobs:

  build:
    executor: nodejs
    steps:
      - prepare
      - build

  prerelease:
    executor: nodejs
    steps:
      - prepare
      - prerelease

  release:
    executor: nodejs
    steps:
      - prepare
      - release

executors:

  nodejs:
    docker:
      - image: cimg/node:lts
    working_directory: ~/iapetus

commands:

  prepare:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "30:af:ba:bc:9b:61:64:66:68:aa:ed:0d:aa:9b:bd:cf"

      - checkout:
          path: ~/iapetus

      - run:
          name: Setup environment
          command: |
            npm install --prefix=$HOME/.local yarn@berry -g
            yarn --version

      - run: 
          name: Install dependencies
          command: |
            (cd ~/iapetus && yarn install --immutable)

      - run:
          name: Setup environment
          command: |
            git config user.email "github@collabsoft.net"
            git config user.name "CollabSoft Bot"

  build:
    steps:
      - run: 
          name: Install dependencies
          command: yarn reinstall

      - run: 
          name: Build
          command: yarn build

  prerelease:
    steps:
      - build

      - run: 
          name: Publish prerelease
          command: yarn prerelease

  release:
    steps:
      - build

      - run: 
          name: Publish
          command: |
            yarn run lerna version --conventional-commits
            yarn run lerna publish --from-git

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: 
                - develop
                - main

      - prerelease:
          filters:
            branches:
              only: develop
              
      - release:
          filters:
            branches:
              only: main
